const fortunes = [
    "You will have a great day!",
    "Success is on your horizon.",
    "Expect a pleasant surprise soon.",
    "Your hard work will soon pay off.",
    "A new opportunity is coming your way.",
    "Happiness is in your future.",
    "You will achieve your goals.",
    "Someone will bring joy to your life.",
    "Good news is on its way.",
    "You will make a valuable new friend.",
    "Your talents will be recognized.",
    "You will experience a stroke of good luck.",
    "A positive change is coming.",
    "You will find something you lost.",
    "You will discover a hidden talent.",
    "An exciting adventure awaits you.",
    "You will be surrounded by love.",
    "A financial gain is coming.",
    "You will overcome a challenge.",
    "You will receive a compliment.",
    "Your efforts will be rewarded.",
    "You will make a positive impact on someone.",
    "A wish you made will come true.",
    "You will find peace and tranquility.",
    "A joyful event is in your future.",
    "You will meet someone inspiring.",
    "Your creativity will flourish.",
    "You will gain a new perspective.",
    "A long-awaited event will happen soon.",
    "You will receive unexpected support.",
    "You will have a reason to celebrate.",
    "Your kindness will be repaid.",
    "You will enjoy good health.",
    "You will accomplish something significant.",
    "You will receive good advice.",
    "Today will be an average day.",
    "You will learn something new.",
    "An old friend will contact you.",
    "You will spend time reflecting.",
    "A familiar routine will bring comfort.",
    "You will have a chance to relax.",
    "A minor change is coming.",
    "You will revisit a favorite hobby.",
    "You will find a moment of solitude.",
    "An ordinary day can be special.",
    "You may face a small disappointment.",
    "Beware of making hasty decisions.",
    "You might encounter a minor setback.",
    "A misunderstanding could arise.",
    "You may need to apologize soon."
];

const randomIndex=Math.floor(Math.random() * (50 - 0 + 1)) + 0;

console.log(fortunes[randomIndex]);
